from .asymmetric_loss import AsymmetricLossMultiLabel, AsymmetricLossSingleLabel
from .binary_cross_entropy import BinaryCrossEntropy
from .cross_entropy import LabelSmoothingCrossEntropy, SoftTargetCrossEntropy,rein_CrossEntropyLoss,rein_LabelSmoothingCrossEntropy,rein_SoftTargetCrossEntropy
from .jsd import JsdCrossEntropy
